mysite/accounts/urls.py
from django.conf.urls import url
from .import views

app_name = 'accounts'

urlpatterns = [
 url(r'^signup/$',views.signup_view,name="signup"),
 url(r'^login/$',views.login_view,name="login"),
 url(r'^logout/$', views.logout_view,name='logout'),
 ]

mysite/articles/urls.py
from django.contrib import admin
from django.conf.urls import url

from . import views

app_name = 'articles'

urlpatterns = [
    
	url(r'^$',views.article_list,name='list'),
	url(r'^create/$',views.article_create, name="create"),
	url(r'^(?P<slug>[\w-]+)/$',views.article_detail,name='detail'),
	#url(r'^(?P<group>[0-9])/$',views.article_group,name='group'),
	
]

mysite/mysite/urls.py

from django.contrib import admin
from django.conf.urls import url,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as articles_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^accounts/',include('accounts.urls')),
	url(r'^articles/', include('articles.urls')), 
	url(r'^about/$',views.about),
	url(r'^$',articles_views.article_list, name = "home"),
	
	
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/accounts/models.py
from django.db import models

# Create your models here.

mysite/articles/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.
class Article(models.Model):
 nazwa = models.CharField(max_length=30)
 slug = models.SlugField()
 komentarz = models.TextField(default = "-",max_length=70)
 date = models.DateTimeField(auto_now_add=True)
 grupa = models.PositiveIntegerField(default = 1)
 file = models.FileField(default = 'Żaden,załaduj go ponownie',blank=False)
 autor = models.ForeignKey(User,on_delete=models.CASCADE,default = None)
 ocena = models.CharField(max_length=1,default = "-")
 #ZROB OCENE, ALE NIE POOKAZUJ JEJ PRZY DODAWANIU PLIKU ocena = models.PositiveIntegerField(default = )
 def __str__(self):
  return self.nazwa
  
 def snippet(self):
   return self.komentarz[:20] 

mysite/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
 class Meta:
  model = models.Article
  fields = ['nazwa','grupa','file','komentarz','slug']

mysite/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout


# Create your views here.
def signup_view(request):

 if request.method =='POST':
  form = UserCreationForm(request.POST)
  if form.is_valid():
     user = form.save()
     #log the ussser	
     login(request,user)	 
     return redirect('articles:list')
 else:
    form = UserCreationForm()
 return render(request,'accounts/signup.html',{'form':form})	
 
 
def login_view(request):
 if request.method == 'POST':
   form = AuthenticationForm(data=request.POST)
   if form.is_valid():
       #log in the user
	   user = form.get_user()
	   login(request,user)
	   if 'next' in request.POST:
	    return redirect(request.POST.get('next'))
	   else:
	    return redirect('articles:list')
 
 
 else:
  form = AuthenticationForm()
 return render(request,'accounts/login.html',{'form':form})
 
 
 
def logout_view(request):
 if request.method == 'POST':
  logout(request)
  return redirect('articles:list')
	

mysite/articles/views.py
from django.shortcuts import render,redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(request):
 articles = Article.objects.all().order_by('grupa','nazwa')
 return render(request,'articles/article_list.html',{'articles':articles})
 
def article_detail(request,slug):
 #return HttpResponse(slug)
 article = Article.objects.get(slug=slug)
 return render(request,'articles/article_detail.html',{'article':article})
#POTEM ZROB GROUPS
#def article_group(request,group):
 #artgroup = Article.objects.get(group=group)
 #return render(request,'articles/article_detail.html',{'artgroup':artgroup}) 
  #return HttpResponse(group)
@login_required(login_url="/accounts/login/")
def article_create(request):
 if request.method == 'POST':
  form=forms.CreateArticle(request.POST,request.FILES)
  if form.is_valid():
   instance = form.save(commit=False)
   instance.autor = request.user
   instance.save()
   return redirect('articles:list')
 else: 
  form = forms.CreateArticle()
 return render(request,'articles/article_create.html',{'form':form })  

mysite/mysite/views.py
from django.http import HttpResponse


from django.shortcuts import render




def about(request):
 #return HttpResponse('about')
 return render(request,'about.html')

mysite/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}
{% block content %}
  <h1>
   “I choose a lazy person to do a hard job. Because a lazy person will find an easy way to do it.” 
  </h1>
  <h2
  style="color:grey;">Bill Gates
  </h2>
  <form class="site-form" action="/accounts/login/" method="post">
    {% csrf_token %}
    {{form}}
	{% if request.GET.next %}
	 <input type = "hidden" name="next" value="{{request.GET.next}}">
	 {% endif %}
 <input type="submit" value="Login"/>
  </form>
  <p>Wciąż nie masz konta?<a href="{% url 'accounts:signup' %}">Stwórz je więc!</a></p>
 
{% endblock %}

mysite/accounts/templates/accounts/signup.html
{% extends 'base_layout.html'%}
{% block content %}
  <h1>
  "Just remember, life is like a box of chocolates..."
  
  </h1>
  
  <h5>
  (Pamiętaj,aby nazwać się przyzwoicie!) </h5>
  <form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    {{form}}
  <input type="submit" value="Stwórz konto">
  </form>
 
{% endblock%}

mysite/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}


{% block content %}
 <div class="create-article">
 
 <h3>Jesteś teraz w trakcie dodawania sprawozdania.Gratulację! Widać, że Ci zależy.
Pamiętaj natomiast by odpowiednio nazwać swój plik = Imię_Nazwisko_Lab'numer'
(NIE ZMIENIAJ NIC W POLU 'SLUG') </h3>
<h4> Przykład: Jan_Nowak_Lab1 </h4>
<h6> Nie zwracaj uwagi na pole "slug" służy do odpowiedniego nazywania Twojego wpisu.NIE NALEŻY GO MODYFIKOWAĆ </h6>
 <form class="site-form" action="/articles/create/" method="post" enctype="multipart/form-data">
 {% csrf_token %}
 {{form}}
 <input type="submit" value="Dodaj sprawozdanie">
 
 </form>
 </div>
 <script src="/static/slugify.js"></script>
{% endblock %}

mysite/articles/templates/articles/article_detail.html
{% extends 'base_layout.html'%}

{%block content%}
<div class="article-detail">
<div class = "article">
<h2>{{article.nazwa}}</h2>
<p>{{article.komentarz}}</p>
<p>{{article.date}}</p>
<p>Grupa:{{article.grupa}}</p>
<p>Wybrany plik:{{article.file}}</p>
<p>Ocena:{{article.ocena}}</p>

</div>
</div>
{%endblock%}

mysite/articles/templates/articles/article_list.html
{% extends 'base_layout.html'%}

{% block content %}

  <h1>
  Repozytorium sprawozdań IS 
  </h1>
  <div class="articles">
  {% for article in articles %}
   <div class='article'>
        <h2><a href="{% url 'articles:detail' slug=article.slug%}">{{article.nazwa}}</a></h2>
		<p>{{article.snippet}}</p>
		<p>{{article.date}}</p>
		<h3>Grupa:{{article.grupa}}</h3>
		<p class="autor"> Dodany przez {{article.autor}}</p>
		</div>
  
  {% endfor %}
 
 {% endblock %}

  
  

mysite/templates/about.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>
  Twórcy: Emil Szpulecki,Mikołąj Obrębski,Szymon Kasprzykowski, Paweł Bieszek
</h1>
  




{% endblock %}

mysite/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
  <title>Article</title>
  <link rel="stylesheet" href="{% static 'style.css'%}">
  
  </head>
  
  <body>
      <div class="wrapper">
	  <h1><a href="{% url 'home' %}">Powrót do strony głównej</a></h1>
	  <nav>
	    <ul>
		{% if user.is_authenticated %}
		<li>
		<form class="logout-link" action="/accounts/logout/" method="post">
		{% csrf_token %}
		<button type="submit">Wyloguj się</button>
		</form>
		</li>
		<li><a href="{% url 'articles:create' %}" class="highlight" >Dodaj sprawozdanie</a></li>
		{% else %}
		<li>
		<a href="{%url 'accounts:login' %}" class="zaloguj" >Zaloguj się</a></li>
		<li>
		<a href="{%url 'accounts:signup'%}" class="zaloguj1" >Stwórz konto </a></li>
		
		
		{% endif %}
		</ul>
	</nav>
	   {% block content %}
	   {% endblock %} 
	  </div>


 </body>
</html>